### ISSUE TITLE
can u give me a sample example or demo 

### ISSUE THREAD

**Issue by mrshiva009** [rodrigooslp/v-select-box#2]
can u provide me a sample of how to write a function for load option and a sample code of pagination for options implemented

**Comment by rodrigooslp** [comment]
Sure, I'll make a simple example in jsfiddle and post here.

**Comment by mrshiva009** [comment]
And do we have any option in custom styling the select options .
although i am sending a function , it is throwing an exception saying to pass a function to load items

**Comment by kinnngg** [comment]
@rodrigooslp we are still waiting for the sample bro :)

**Comment by rodrigooslp** [comment]
The demo is [here](https://github.com/rodrigooslp/v-select-box-example)
